# .circleci/config.yml
version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: julia:0.7                # image comes from Docker hub
    steps:
      - checkout
      - restore_cache:
          keys:
            - source #one time, not every time!
      - run:
          name: install deps 
          command: julia -e 'using Pkg; Pkg.update(); Pkg.add("PlotlyJS");'
      - save_cache:
          key: source 
          paths:
            - ".git"
      - run:
          name: transform jl to md
          command: julia -e 'include("docs/build_example_docs.jl");'    