version: 2.1

jobs:
  build-doc:
    resource_class: xlarge
    docker:
      - image: julia:1.6.2-buster

    steps:
      - add_ssh_keys:
          fingerprints:
            - "dc:5f:39:48:00:b4:72:34:e1:d2:c4:e1:1f:d1:e2:ce" #plotlydocbot

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Manifest.toml" }}

      - run:
          name: install dependencies
          command: |
            apt update && apt install -y unzip zip make git
            echo 'export JULIA_PKG_SERVER=""' >> $BASH_ENV
            julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate()'

      - save_cache:
          paths:
            - /root/.julia
          key: v1-dependencies-{{ checksum "Manifest.toml" }}

      - run:
          name: make html
          command: |
            echo ${mapbox_token} > julia/.mapbox_token
            make html || make html
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd build/html
              git init
              git config user.name plotlydocbot
              git config user.email accounts@plot.ly
              git add *
              git commit -m "build of https://github.com/plotlyplotlyjs.jl-docs/commit/${CIRCLE_SHA1}"
              git push --force git@github.com:plotly/plotlyjs.jl-docs.git master:built
              rm -rf .git
              cd ../..
            fi
            tar -zcf build/html.tgz build/html
            rm -rf build/html

      - store_artifacts:
          path: build
          destination: build

workflows:
  build:
    jobs:
      - build-doc
